"""add enhancements to retrieval endpoints

Revision ID: 0c6c449e0257
Revises: 79fabdf0c994
Create Date: 2024-11-04 17:13:39.695601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6c449e0257'
down_revision: Union[str, None] = '79fabdf0c994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
