"""Add fixtures and venues

Revision ID: 0ecead57cc7e
Revises: f6ef510d34b1
Create Date: 2024-11-01 22:55:44.043931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecead57cc7e'
down_revision: Union[str, None] = 'f6ef510d34b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
