"""bookmakers schema

Revision ID: 1bbfdcf36f3c
Revises: 082ea5f5abef
Create Date: 2024-11-02 12:56:48.172187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbfdcf36f3c'
down_revision: Union[str, None] = '082ea5f5abef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fixture_odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.fixture_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixture_bookmakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_odds_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['fixture_odds_id'], ['fixture_odds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('bet_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bet_type_id'], ['bet_types.id'], ),
    sa.ForeignKeyConstraint(['fixture_bookmaker_id'], ['fixture_bookmakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odd_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('odd', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odd_values')
    op.drop_table('bets')
    op.drop_table('fixture_bookmakers')
    op.drop_table('fixture_odds')
    op.drop_table('bookmakers')
    op.drop_table('bet_types')
    # ### end Alembic commands ###
