"""Add is_final column to Fixture model

Revision ID: 1ece1450d53f
Revises: ed1f4a473392
Create Date: 2024-11-14 13:54:05.219165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ece1450d53f'
down_revision: Union[str, None] = 'ed1f4a473392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('appearances', sa.Integer(), nullable=True),
    sa.Column('lineups', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('captain', sa.Boolean(), nullable=True),
    sa.Column('subs_in', sa.Integer(), nullable=True),
    sa.Column('subs_out', sa.Integer(), nullable=True),
    sa.Column('subs_bench', sa.Integer(), nullable=True),
    sa.Column('shots_total', sa.Integer(), nullable=True),
    sa.Column('shots_on', sa.Integer(), nullable=True),
    sa.Column('goals_total', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('goals_assists', sa.Integer(), nullable=True),
    sa.Column('goals_saves', sa.Integer(), nullable=True),
    sa.Column('passes_total', sa.Integer(), nullable=True),
    sa.Column('passes_key', sa.Integer(), nullable=True),
    sa.Column('passes_accuracy', sa.Integer(), nullable=True),
    sa.Column('tackles_total', sa.Integer(), nullable=True),
    sa.Column('tackles_blocks', sa.Integer(), nullable=True),
    sa.Column('tackles_interceptions', sa.Integer(), nullable=True),
    sa.Column('duels_total', sa.Integer(), nullable=True),
    sa.Column('duels_won', sa.Integer(), nullable=True),
    sa.Column('dribbles_attempts', sa.Integer(), nullable=True),
    sa.Column('dribbles_success', sa.Integer(), nullable=True),
    sa.Column('dribbles_past', sa.Integer(), nullable=True),
    sa.Column('fouls_drawn', sa.Integer(), nullable=True),
    sa.Column('fouls_committed', sa.Integer(), nullable=True),
    sa.Column('cards_yellow', sa.Integer(), nullable=True),
    sa.Column('cards_yellowred', sa.Integer(), nullable=True),
    sa.Column('cards_red', sa.Integer(), nullable=True),
    sa.Column('penalty_won', sa.Integer(), nullable=True),
    sa.Column('penalty_committed', sa.Integer(), nullable=True),
    sa.Column('penalty_scored', sa.Integer(), nullable=True),
    sa.Column('penalty_missed', sa.Integer(), nullable=True),
    sa.Column('penalty_saved', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_statistics_id'), 'player_statistics', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('win_or_draw', sa.Boolean(), nullable=True),
    sa.Column('under_over', sa.String(), nullable=True),
    sa.Column('goals_home', sa.String(), nullable=True),
    sa.Column('goals_away', sa.String(), nullable=True),
    sa.Column('advice', sa.String(), nullable=True),
    sa.Column('percent_home', sa.String(), nullable=True),
    sa.Column('percent_draw', sa.String(), nullable=True),
    sa.Column('percent_away', sa.String(), nullable=True),
    sa.Column('comparison', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.fixture_id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.alter_column('fixtures', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixtures', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_player_statistics_id'), table_name='player_statistics')
    op.drop_table('player_statistics')
    # ### end Alembic commands ###
