"""Update models with cascading deletes and unique constraints

Revision ID: 20d19614b566
Revises: 7de43d2b7ba6
Create Date: 2024-12-02 14:31:43.331502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d19614b566'
down_revision: Union[str, None] = '7de43d2b7ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bets_fixture_bookmaker_id_fkey', 'bets', type_='foreignkey')
    op.create_foreign_key(None, 'bets', 'fixture_bookmakers', ['fixture_bookmaker_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fixture_bookmakers_fixture_odds_id_fkey', 'fixture_bookmakers', type_='foreignkey')
    op.create_foreign_key(None, 'fixture_bookmakers', 'fixture_odds', ['fixture_odds_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'fixture_odds', ['fixture_id'])
    op.drop_constraint('fixture_odds_fixture_id_fkey', 'fixture_odds', type_='foreignkey')
    op.create_foreign_key(None, 'fixture_odds', 'fixtures', ['fixture_id'], ['fixture_id'], ondelete='CASCADE')
    op.drop_constraint('fixtures_venue_id_fkey', 'fixtures', type_='foreignkey')
    op.create_foreign_key(None, 'fixtures', 'venues', ['venue_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('match_events_fixture_id_fkey', 'match_events', type_='foreignkey')
    op.create_foreign_key(None, 'match_events', 'fixtures', ['fixture_id'], ['fixture_id'], ondelete='CASCADE')
    op.create_unique_constraint('match_statistics_fixture_team_key', 'match_statistics', ['fixture_id', 'team_id'])
    op.drop_constraint('match_statistics_fixture_id_fkey', 'match_statistics', type_='foreignkey')
    op.create_foreign_key(None, 'match_statistics', 'fixtures', ['fixture_id'], ['fixture_id'], ondelete='CASCADE')
    op.drop_constraint('odd_values_bet_id_fkey', 'odd_values', type_='foreignkey')
    op.create_foreign_key(None, 'odd_values', 'bets', ['bet_id'], ['id'], ondelete='CASCADE')
    op.alter_column('predictions', 'fixture_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('predictions_fixture_id_fkey', 'predictions', type_='foreignkey')
    op.create_foreign_key(None, 'predictions', 'fixtures', ['fixture_id'], ['fixture_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.create_foreign_key('predictions_fixture_id_fkey', 'predictions', 'fixtures', ['fixture_id'], ['fixture_id'])
    op.alter_column('predictions', 'fixture_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'odd_values', type_='foreignkey')
    op.create_foreign_key('odd_values_bet_id_fkey', 'odd_values', 'bets', ['bet_id'], ['id'])
    op.drop_constraint(None, 'match_statistics', type_='foreignkey')
    op.create_foreign_key('match_statistics_fixture_id_fkey', 'match_statistics', 'fixtures', ['fixture_id'], ['fixture_id'])
    op.drop_constraint('match_statistics_fixture_team_key', 'match_statistics', type_='unique')
    op.drop_constraint(None, 'match_events', type_='foreignkey')
    op.create_foreign_key('match_events_fixture_id_fkey', 'match_events', 'fixtures', ['fixture_id'], ['fixture_id'])
    op.drop_constraint(None, 'fixtures', type_='foreignkey')
    op.create_foreign_key('fixtures_venue_id_fkey', 'fixtures', 'venues', ['venue_id'], ['id'])
    op.drop_constraint(None, 'fixture_odds', type_='foreignkey')
    op.create_foreign_key('fixture_odds_fixture_id_fkey', 'fixture_odds', 'fixtures', ['fixture_id'], ['fixture_id'])
    op.drop_constraint(None, 'fixture_odds', type_='unique')
    op.drop_constraint(None, 'fixture_bookmakers', type_='foreignkey')
    op.create_foreign_key('fixture_bookmakers_fixture_odds_id_fkey', 'fixture_bookmakers', 'fixture_odds', ['fixture_odds_id'], ['id'])
    op.drop_constraint(None, 'bets', type_='foreignkey')
    op.create_foreign_key('bets_fixture_bookmaker_id_fkey', 'bets', 'fixture_bookmakers', ['fixture_bookmaker_id'], ['id'])
    # ### end Alembic commands ###
