"""Fix TeamLeague relationships and remove deprecated fields

Revision ID: 23711cb3d1f2
Revises: b3357e1f5c7f
Create Date: 2024-12-15 23:58:28.300478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23711cb3d1f2'
down_revision: Union[str, None] = 'b3357e1f5c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
