"""Rename 'end' to 'end_date' and add 'start_date' to seasons

Revision ID: 69b22f874af9
Revises: d9d904af57ef
Create Date: 2024-12-15 12:13:23.829845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b22f874af9'
down_revision: Union[str, None] = 'd9d904af57ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'league_id', 'season_year', name='uix_team_league_season')
    )
    op.create_index(op.f('ix_team_leagues_id'), 'team_leagues', ['id'], unique=False)
    op.alter_column('seasons', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_league_year_season', 'seasons', type_='unique')
    op.drop_constraint('teams_league_id_fkey', 'teams', type_='foreignkey')
    op.drop_column('teams', 'league_id')
    op.drop_column('teams', 'season_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('season_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('teams_league_id_fkey', 'teams', 'leagues', ['league_id'], ['league_id'])
    op.create_unique_constraint('uq_league_year_season', 'seasons', ['league_id', 'year'])
    op.alter_column('seasons', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_team_leagues_id'), table_name='team_leagues')
    op.drop_table('team_leagues')
    # ### end Alembic commands ###
