"""Enhance TeamLeagueSchema with team relationship

Revision ID: 6a008066e322
Revises: 23711cb3d1f2
Create Date: 2024-12-16 00:02:00.661261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a008066e322'
down_revision: Union[str, None] = '23711cb3d1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
