"""Add team_id to MatchStatistics

Revision ID: 7de43d2b7ba6
Revises: e969ec07a7a7
Create Date: 2024-12-02 14:11:00.648018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de43d2b7ba6'
down_revision: Union[str, None] = 'e969ec07a7a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_statistics', sa.Column('team_id', sa.Integer(), nullable=False))
    op.alter_column('match_statistics', 'fixture_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('match_statistics_fixture_id_key', 'match_statistics', type_='unique')
    op.create_index(op.f('ix_match_statistics_id'), 'match_statistics', ['id'], unique=False)
    op.create_foreign_key(None, 'match_statistics', 'teams', ['team_id'], ['team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_statistics', type_='foreignkey')
    op.drop_index(op.f('ix_match_statistics_id'), table_name='match_statistics')
    op.create_unique_constraint('match_statistics_fixture_id_key', 'match_statistics', ['fixture_id'])
    op.alter_column('match_statistics', 'fixture_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('match_statistics', 'team_id')
    # ### end Alembic commands ###
