"""Add TeamLeague association table

Revision ID: b3357e1f5c7f
Revises: 69b22f874af9
Create Date: 2024-12-15 19:27:14.479620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3357e1f5c7f'
down_revision: Union[str, None] = '69b22f874af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
