"""Add composite foreign key to TeamLeague

Revision ID: c46aa7540efa
Revises: 6a008066e322
Create Date: 2024-12-16 00:07:11.920229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46aa7540efa'
down_revision: Union[str, None] = '6a008066e322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_league_year', 'seasons', ['league_id', 'year'])
    op.create_foreign_key(None, 'team_leagues', 'seasons', ['league_id', 'season_year'], ['league_id', 'year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_leagues', type_='foreignkey')
    op.drop_constraint('uix_league_year', 'seasons', type_='unique')
    # ### end Alembic commands ###
