"""Add start_date and end_date to seasons

Revision ID: d9d904af57ef
Revises: 40a6962486c6
Create Date: 2024-12-14 15:35:33.261220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d904af57ef'
down_revision: Union[str, None] = '40a6962486c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fixtures_away_team_id_fkey', 'fixtures', type_='foreignkey')
    op.drop_constraint('fixtures_home_team_id_fkey', 'fixtures', type_='foreignkey')
    op.create_foreign_key(None, 'fixtures', 'teams', ['away_team_id'], ['team_id'])
    op.create_foreign_key(None, 'fixtures', 'teams', ['home_team_id'], ['team_id'])
    op.drop_constraint('match_events_team_id_fkey', 'match_events', type_='foreignkey')
    op.create_foreign_key(None, 'match_events', 'teams', ['team_id'], ['team_id'])
    op.drop_constraint('match_statistics_team_id_fkey', 'match_statistics', type_='foreignkey')
    op.create_foreign_key(None, 'match_statistics', 'teams', ['team_id'], ['team_id'])
    op.drop_constraint('player_statistics_team_id_fkey', 'player_statistics', type_='foreignkey')
    op.create_foreign_key(None, 'player_statistics', 'teams', ['team_id'], ['team_id'])
    op.drop_constraint('players_team_id_fkey', 'players', type_='foreignkey')
    op.create_foreign_key(None, 'players', 'teams', ['team_id'], ['team_id'])
    op.drop_constraint('predictions_winner_team_id_fkey', 'predictions', type_='foreignkey')
    op.create_foreign_key(None, 'predictions', 'teams', ['winner_team_id'], ['team_id'])
    op.add_column('seasons', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('seasons', sa.Column('end_date', sa.Date(), nullable=True))
    op.alter_column('seasons', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_league_year_season', 'seasons', ['league_id', 'year'])
    op.drop_column('seasons', 'end')
    op.drop_column('seasons', 'start')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('start', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('seasons', sa.Column('end', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_league_year_season', 'seasons', type_='unique')
    op.alter_column('seasons', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('seasons', 'end_date')
    op.drop_column('seasons', 'start_date')
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.create_foreign_key('predictions_winner_team_id_fkey', 'predictions', 'teams', ['winner_team_id'], ['team_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.create_foreign_key('players_team_id_fkey', 'players', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'player_statistics', type_='foreignkey')
    op.create_foreign_key('player_statistics_team_id_fkey', 'player_statistics', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'match_statistics', type_='foreignkey')
    op.create_foreign_key('match_statistics_team_id_fkey', 'match_statistics', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'match_events', type_='foreignkey')
    op.create_foreign_key('match_events_team_id_fkey', 'match_events', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'fixtures', type_='foreignkey')
    op.drop_constraint(None, 'fixtures', type_='foreignkey')
    op.create_foreign_key('fixtures_home_team_id_fkey', 'fixtures', 'teams', ['home_team_id'], ['team_id'], ondelete='CASCADE')
    op.create_foreign_key('fixtures_away_team_id_fkey', 'fixtures', 'teams', ['away_team_id'], ['team_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
