"""Add season_year to Team and Player

Revision ID: ee03525f32cd
Revises: ac8c3fe438ff
Create Date: 2024-11-01 12:33:17.110961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee03525f32cd'
down_revision: Union[str, None] = 'ac8c3fe438ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('season_year', sa.Integer(), nullable=False))
    op.add_column('teams', sa.Column('season_year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'season_year')
    op.drop_column('players', 'season_year')
    # ### end Alembic commands ###
