"""Add is_final column to Fixture model

Revision ID: f6ccb2bb2999
Revises: 1ece1450d53f
Create Date: 2024-11-14 14:52:54.711305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ccb2bb2999'
down_revision: Union[str, None] = '1ece1450d53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('is_final', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixtures', 'is_final')
    # ### end Alembic commands ###
