"""Add fixtures and venues

Revision ID: f6ef510d34b1
Revises: 0c8ae4c7d014
Create Date: 2024-11-01 22:36:22.205497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ef510d34b1'
down_revision: Union[str, None] = '0c8ae4c7d014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_table('fixtures',
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('referee', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('status_long', sa.String(), nullable=False),
    sa.Column('status_short', sa.String(), nullable=False),
    sa.Column('status_elapsed', sa.Integer(), nullable=True),
    sa.Column('status_extra', sa.String(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('round', sa.String(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('goals_home', sa.Integer(), nullable=True),
    sa.Column('goals_away', sa.Integer(), nullable=True),
    sa.Column('score_halftime_home', sa.Integer(), nullable=True),
    sa.Column('score_halftime_away', sa.Integer(), nullable=True),
    sa.Column('score_fulltime_home', sa.Integer(), nullable=True),
    sa.Column('score_fulltime_away', sa.Integer(), nullable=True),
    sa.Column('score_extratime_home', sa.Integer(), nullable=True),
    sa.Column('score_extratime_away', sa.Integer(), nullable=True),
    sa.Column('score_penalty_home', sa.Integer(), nullable=True),
    sa.Column('score_penalty_away', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('fixture_id')
    )
    op.create_index(op.f('ix_fixtures_fixture_id'), 'fixtures', ['fixture_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixtures_fixture_id'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###
